board:
  size: 10
  obstacleDensity: 0.05
  fogOfWar:
    enabled: true
    viewRadius: 3  # Number of cells a tank can see in each direction

game:
  currentPlayers: 4         # For testing this add X Example Bots
  tournament:
    enabled: false
    min: 2
    roundRobinRepetitions: 5      # Number of times each pair plays
  stalemateDetection:
    enabled: true
    maxStateRepetitions: 10    # Number of times a state can repeat before stalemate
    maxUnchangedTurns: 20      # Number of turns without changes before stalemate
    turnsToCheck: 40           # Number of past turns to check


players:
  min: 2
  max: 4
  movesPerTurn: 3

tank:
  initialHealth: 100
  shootRange: 5
  damagePerShot: 25

view:
  enabled: true       # Set to false for headless mode
  clearScreen: true   # Set to false if terminal doesn't support ANSI clear
  moveDelay: 250       # Milliseconds between moves
  colorEnabled: true   # Set to false if terminal doesn't support ANSI colors

max_turns: 1000  # Set the maximum number of turns allowed before declaring a draw